[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "salvajson"
version = "0.1.0"
description = "A Python package for parsing corrupted JSON files using jsonic"
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
dependencies = [
    "pythonmonkey>=0.5.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/salvajson"]

[tool.hatch.build]
include = [
    "src/salvajson/*.py",
    "src/salvajson/salvajson.js"
]

[tool.hatch.build.targets.sdist]
include = [
    "src/salvajson",
    "js_src",
    "build.py",
    "README.md",
    "pyproject.toml"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
