[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "salvajson"
version = "0.1.0"
description = "A Python package for parsing corrupted JSON files using jsonic"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = [
    "pythonmonkey>=0.5.0"
]

[tool.hatch.build.targets.wheel]
packages = ["salvajson"]

[tool.hatch.build]
include = [
    "salvajson/*.py",
    "salvajson/salvajson.js"
]

[tool.hatch.build.targets.sdist]
include = [
    "salvajson",
    "js_src",
    "build.py",
    "README.md",
    "pyproject.toml"
]
